#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

FROM nvcr.io/nvidia/pytorch:22.02-py3

USER root

RUN \
    pip3 install torch-tb-profiler && \
    pip3 install opencv-python && \
    pip3 install humanfriendly && \
    pip3 install gpustat
